jmad/core/urls.py
from django.conf.urls import url
from django.contrib import admin

from apps.solos.views import index, solo_detail

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(
        r'^recordings/(?P<album>[\w-]+)/(?P<track>[\w-]+)/(?P<artist>[\w-]+)/$',
        solo_detail,
        name='solo_detail_view'
    ),
    url(r'^$', index),
]

jmad/apps/albums/models.py
from django.db import models


class Album(models.Model):
    name = models.CharField(max_length=100)
    artist = models.CharField(max_length=100)
    slug = models.SlugField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Track(models.Model):
    name = models.CharField(max_length=100)
    album = models.ForeignKey(Album)
    track_number = models.PositiveIntegerField(null=True)
    slug = models.SlugField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['album', 'track_number']

jmad/apps/solos/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.text import slugify

import musicbrainzngs as mb

from apps.albums.models import Album, Track


mb.set_useragent('JMAD - http://jmad.us', version='0.0.1')


class Solo(models.Model):
    track = models.ForeignKey(Track)
    artist = models.CharField(max_length=100)
    instrument = models.CharField(max_length=50)
    start_time = models.CharField(max_length=20, blank=True)
    end_time = models.CharField(max_length=20, blank=True)
    slug = models.SlugField()

    class Meta:
        ordering = ['track', 'start_time']

    @classmethod
    def get_artist_tracks_from_musicbrainz(cls, artist):
        search_results = mb.search_artists(artist)
        best_result = search_results['artist-list'][0]
        instrument = Solo.get_instrument_from_musicbrainz_tags(best_result['tag-list'])

        for album_dict in mb.browse_releases(best_result['id'], includes=['recordings'])['release-list']:
            album = Album.objects.create(
                name=album_dict['title'],
                artist=artist,
                slug=slugify(album_dict['title'])
            )

            for track_dict in album_dict['medium-list']:
                track = Track.objects.create(
                    album=album,
                    name=track_dict['recording']['title'],
                    track_number=track_dict['position'],
                    slug=slugify(track_dict['recording'['title']])
                )

                Solo.objects.create(
                    track=track, artist=artist,
                    instrument=instrument, slug=slugify(artist)
                )

        return Solo.objects.filter(artist=artist)

    def get_absolute_url(self):
        return reverse('solo_detail_view', kwargs={
            'album': self.track.album.slug,
            'track': self.track.slug,
            'artist': self.slug
        })

    def get_duration(self):
        duration_string = ''
        if self.start_time and self.end_time:
            duration_string = '{}-{}'.format(self.start_time, self.end_time)
        return duration_string

jmad/apps/albums/views.py
from django.shortcuts import render

# Create your views here.

jmad/apps/solos/views.py
from django.shortcuts import render

from .models import Solo


def solo_detail(request, album, track, artist):
    context = {
        'solo': Solo.objects.get(slug=artist, track__slug=track, track__album__slug=album)
    }
    return render(request, 'solos/solo_detail.html', context)


def index(request):
    context = {'solos': []}

    if request.GET.keys():
        solos_queryset = Solo.objects.all()

        if request.GET.get('instrument', None):
            solos_queryset = solos_queryset.filter(
                instrument=request.GET.get('instrument', None)
            )

        artist_kwarg = request.GET.get('artist', None)
        if artist_kwarg:
            solos_queryset = solos_queryset.filter(artist=artist_kwarg)

        context['solos'] = solos_queryset

        if context['solos'].count() == 0 and artist_kwarg:
            context['solos'] = Solo.get_artist_tracks_from_musicbrainz(artist_kwarg)

    return render(request, 'solos/index.html', context)

jmad/apps/solos/templates/solos/index.html
<a href="" class="navbar-brand">JMAD</a>

<form action="">
    <label for="jmad-instrument">Instrument</label>
    <input type="text" class="form-control" id="jmad-instrument" name="instrument" placeholder="i.e. trumpet">
    <label for="jmad-artist">Artist</label>
    <input type="text" class="form-control" id="jmad-artist" name="artist" placeholder="i.e. Davis">
    <button type="submit">Search JMAD</button>
</form>

{% for solo in solos %}
    <div class="jmad-search-result">
        <a href="{{ solo.get_absolute_url }}">
            {{ solo.track.name }} : {{ solo.artist }} on {{ solo.instrument }}
        </a>
    </div>
{% endfor %}

jmad/apps/solos/templates/solos/solo_detail.html
<p id="jmad-artist">{{ solo.artist }}</p>
<p id="jmad-track">
    {{ solo.track.name }}
    {% with solos=solo.track.solo_set.count %}
        [{{ solos }} solo{{ solos|pluralize }}]
    {% endwith %}
</p>
<p id="jmad-album">
    {{ solo.track.album.name }}
    {% with tracks=solo.track.album.track_set.count %}
        [{{ tracks }} track{{ tracks|pluralize }}]
    {% endwith %}
</p>
<p id="jmad-start-time">{{ solo.start_time }}</p>
<p id="jmad-end-time">{{ solo.end_time }}</p>